name: Testing on Windows
on:
  - push
  - pull_request
permissions:
  contents: read

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby
      min_version: 3.2
  build:
    needs: ruby-versions
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        ruby: ${{ fromJson(needs.ruby-versions.outputs.versions) }}
        exclude:
          - ruby: head
        os:
          - windows-latest
    name: Ruby ${{ matrix.ruby }} unit testing on ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: unit testing
      env:
        CI: true
      run: |
        gem install bundler rake
        bundle install --jobs 4 --retry 3
        bundle exec rake test
